FROM ghcr.io/siemens/kas/kas:3.1

#install dependences:
RUN sudo apt update && apt-get install -y -q \
    build-essential \
    sudo \
    tofrodos \
    iproute2 \
    gawk \
    net-tools \
    expect \
    libncurses5-dev \
    tftpd \
    update-inetd \
    libssl-dev \
    flex \
    bison \
    mtools \
    libselinux1 \
    gnupg \
    wget \
    socat \
    gcc-multilib \
    libsdl1.2-dev \
    libglib2.0-dev \
    lib32z1-dev \
    libgtk2.0-0 \
    screen \
    pax \
    diffstat \
    xvfb \
    xterm \
    texinfo \
    gzip \
    unzip \
    cpio \
    chrpath \
    autoconf \
    lsb-release \
    libtool \
    libtool-bin \
    locales \
    kmod \
    git \
    rsync \
    libconfuse-dev \
    dosfstools \
    bc \
    python \
    python3 \
    u-boot-tools \
    libconfuse-dev \
    gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev zstd liblz4-tool \
    locales-all

RUN sudo apt install libtinfo5 libtinfo-dev -y
